sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: mRD9Ta0lhMd7vDR4RblTl44VYk6TEK7iUuVHp4U3FncTvOckPgln/+un8zZNciujBbb6Pwa/iZyYmNioWk4uqHM6CzSN4NQeRJGIYA9jCseU9BfoZp2HLgd465leSkIBUUe7N5hMP84PJwgWfKcwLsvOt+VMC2AKDyOYDXa6qxszlYVg86BfYHDUi1TmkX64p5iDPqdWDO6fS83GRaqzupNaiprqFYC3nttYuWv0x7v7+q2aYVrPwe/fsxKRBCKNW4WRZobRWQsJxFWvHswXUIgPsvqB3YVDxi6IYAxxuQaa5iYyj9K66BfnLbruZGNClCQd+8Q0ITKOHMtOpplyXzqRlJ9knYwSag4/cki5cpsD1rJW8tqd+TONMHhiawKeYSbg3Vq6ZjQ+qPJkENVty+r3lSBb8X6xf3Q0zCprSEw+Fm6+UugfyqjyMtiZ2CICh4M1yxwprcLHn2se0KpvAUrA42J4kldoAR0BcpOFG4Dfzsx0gAep2Bur3pivCWhgGLplBuaReYrJFJnKeum/ZYvdtzESjqHarwcncsfVMahcm/7fEVhSOPVWZMV+G1X/2BeFk0sQo2TTh03UrqaLtL/Amctl8rQHJfiBgIy4G95OolSIPEvF+WYkFe3ydBVvDgkWuO18xJJwx1mpiSXH7SEURlVpyplZa0ycWv2633Y=
  - secure: En5vayqJFi3r8LNspICM+X0FhKAflpoEq10DwfrPHadzhmvGp2EPXH8nNmiAgBsYvAzdgW5lECPuexswMi6PmaLl+hAMlOb7hRrTjrAvp5X/8QpWhjxGlRDGdRItAwdMDoJ6CdYEzjl2y65ferlWYn59DVTy8C2RgcQsJA33UWTqBX9dB/QPG+JmgJ0gNoXkLkAlaAEp8Y7jw8uhDJg4Jq00fPgECZiBzV/I2WhZRs9gUtbTKi9IX3meY5agVAJ+NuGTD3WSwgS2vRUNBh/HBsXsZfa477hWRdbfOYkMnRoWdq/GGLPzMJLJ186TkVnJuBCBOlIzsmYbuhi7onLatQRpzJFl5K9Qtsm4N0sZCEDyKZenzjyjzoek8j2RIk7jiZ85akCpe6tWlXl5qfbyWpMFxifWZkyV3zQuH3KSEe1dWgN5RKTLjDNvMWVi7qcx2khR7E0GW/JADub6aO3Y0eBX290eNWyzkkJAaPpiYmQC4BHvnNawDBuP5py1iHDn7fAS6c6QLIrXQ8wji4JdOJ2cXRVvvuYW02U0BEdAEBWyJoV8p9v6HjhpOTlfzOxoqv7pKYWkDv15X145M5Jz6pV1SeIiqd5k3yXs36iE+Z3NP8N53gfno+c4Gs3X/jTaadp9Z6zR2MXicz82yiiplW38HsCfrrKvVRlIszUV1Q4=
