language: node_js
sudo: false
node_js: stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- wct --plugin sauce --skip-plugin local
env:
  global:
  - secure: f9gb+qppGe4rCfYtDNmAxPBzVgbQEecOtG56lZoW4Wh3LD2JOxhDiX9aMd5KZ73ZTQQLIFrMTFFH+XTfA6SwzWNV5nGTJQaYmZGFZ0wSgdsDTeUJsVwYTDl8TX0eXpojwFSMBeEsWnmrzlD/gxrYVHOkdM1FqSq5ZVMW2jYAx0ByiJVEGPPexVBQO3lMm3MyS79/1kV2ho3p6F2Ejhu03A/XJzX+nja+2sZToC3/PS8jnQVti7WjzEILnSHX35vdBzZJVBYWxvWnmOiG2Ju0Ubte2u4JV67EMteFUFvskvCCVJGLXJwIFHxBrFZZTHFvRzI/7ryAwg9Jc8n4yf9zf46uPx9I6VWf1zYgagAt6yzz/qjNxqwBao9AOvUJHBVLXruin5dprTD8SxQ6aECcQTfeApHL0pZcTj45sqvT78YQi+Py5ManYIefCetbkooWpBCOZfJCgvlB6UWNltVVlZPjEFm/2ckvOB7i3M2hXupL4yfuixSWhmyEzgrSlwSSf9XYMwq48R46Qopbiif0gb4CWG464g3qi0nevz/4ECDFR2vFrg/+edMQexWxSuaUFtbih1EvHZgij+S4AykMaSpc4NwNkNEonyOjN2rSOCedAStRev4TgD/XuWH3uwGy5Ppt2/1RvaB7lYhAtGlNy+9Fmn5VZszmQE6cph+tw0I=
  - secure: 0Z7Iyceg0ySLXCxKZzHAjlEXP+e3+2sokuFUHwdVUYj/8p24Mk6syAyHR6Hmd1onIza19v2JUuNihT5gHlKmfRvJvZOJRWnWh9mZC83Ss+p/87ONGOF/xzGskB9DQzedpbF00K48v1ETG/GeHvvJd1/f6t2GOSnxE8vifhWny8zU3LUpwhEfh2I2GLgp+gfs1inOcM/oJyWkbUpNPnE8rxBuI0TOJzuSvLpxUxlPYLou/bxu6GLkilHd3k2XMWWLjuWx+azVVEJ0m+w2mEmXaM/qTxuVrRuan/UrrTcoWxgKB46405r2xDr0Beve9VAs4cuXbZycYZ+MSLaGLzqdYAHD2GwZiAOA5D6caN57ogwuJrpf3SnJ0Q5E7XvfJt/TCs/upmQFqhtL7nOjOsJ+Q9ZD+PkzZJOdPK99+wN1NnV71t4aG6bE79zaBjKEhJZkn9xxWWPM9+2Mu4bq+Je1kcoM9mv+BNL47fkPfVG/XEMZFgx1/cPkagv6xBBV8uOW9M7b7BVsM3SG2lTqQMe4pMQCN6ea4CS6JWWK+cPxjY9iIYWbK1KnVebngkhHcU31RVpahJrZfDQMMVG9oPkXv/MT4DMySpnzMxRcCxq9zAh8f5kied8DFTZd0G0LaRyRfpCqxuQulZYeNPHLqhgbgN5qsjmMsR09eRaXbDEvOC8=
